esphome:
  name: "test-fan"
  friendly_name: Test Fan
  min_version: 2024.11.0
  name_add_mac_suffix: false

external_components:
  - source: components

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}

remote_receiver:
  pin:
    number: GPIO14
    inverted: True
    mode: OUTPUT_OPEN_DRAIN
    allow_other_uses: True
  tolerance: 55%
  id: ir_receiver
  buffer_size: 2kb
  
remote_transmitter:
  carrier_duty_percent: 50%
  pin:
    number: GPIO14
    inverted: True
    mode: OUTPUT_OPEN_DRAIN
    allow_other_uses: True

i2c:
  sda: GPIO04
  scl: GPIO05
  scan: true
  id: bus_a
  frequency: 800kHz

fan:
  - platform: panafan
    model: f409m
    id: my_fan
    name: "Fan Controller"
    address: 0x20
    i2c_id: bus_a
    receiver_id: ir_receiver